package com.jcs.blanksheet.utils

import kotlin.math.abs

/**
 * Created by Jardson Costa on 22/03/2021.
 */
class ColorGenerator private constructor(colorList: List<Int>) {
    private val mColors: List<Int> = colorList

    fun getColor(key: Any): Int {
        return mColors[abs(key.hashCode()) % mColors.size]
    }

    companion object {
        var MATERIAL: ColorGenerator

        init {
            MATERIAL = create(
               listOf(
                  MaterialColors.RED_400,
                  MaterialColors.RED_500,
                  MaterialColors.RED_600,
                  MaterialColors.RED_700,
                  MaterialColors.RED_800,
                  MaterialColors.RED_900,
                  MaterialColors.RED_A200,
                  MaterialColors.RED_A400,
                  MaterialColors.RED_A700,
                  MaterialColors.PINK_400,
                  MaterialColors.PINK_500,
                  MaterialColors.PINK_600,
                  MaterialColors.PINK_700,
                  MaterialColors.PINK_800,
                  MaterialColors.PINK_900,
                  MaterialColors.PINK_A200,
                  MaterialColors.PINK_A400,
                  MaterialColors.PINK_A700,
                  MaterialColors.PURPLE_400,
                  MaterialColors.PURPLE_500,
                  MaterialColors.PURPLE_600,
                  MaterialColors.PURPLE_700,
                  MaterialColors.PURPLE_800,
                  MaterialColors.PURPLE_900,
                  MaterialColors.PURPLE_A200,
                  MaterialColors.PURPLE_A400,
                  MaterialColors.PURPLE_A700,
                  MaterialColors.DEEPPURPLE_400,
                  MaterialColors.DEEPPURPLE_500,
                  MaterialColors.DEEPPURPLE_600,
                  MaterialColors.DEEPPURPLE_700,
                  MaterialColors.DEEPPURPLE_800,
                  MaterialColors.DEEPPURPLE_900,
                  MaterialColors.DEEPPURPLE_A200,
                  MaterialColors.DEEPPURPLE_A400,
                  MaterialColors.DEEPPURPLE_A700,
                  MaterialColors.INDIGO_400,
                  MaterialColors.INDIGO_500,
                  MaterialColors.INDIGO_600,
                  MaterialColors.INDIGO_700,
                  MaterialColors.INDIGO_800,
                  MaterialColors.INDIGO_900,
                  MaterialColors.INDIGO_A200,
                  MaterialColors.INDIGO_A400,
                  MaterialColors.INDIGO_A700,
                  MaterialColors.BLUE_400,
                  MaterialColors.BLUE_500,
                  MaterialColors.BLUE_600,
                  MaterialColors.BLUE_700,
                  MaterialColors.BLUE_800,
                  MaterialColors.BLUE_900,
                  MaterialColors.BLUE_A200,
                  MaterialColors.BLUE_A400,
                  MaterialColors.BLUE_A700,
                  MaterialColors.LIGHTBLUE_400,
                  MaterialColors.LIGHTBLUE_500,
                  MaterialColors.LIGHTBLUE_600,
                  MaterialColors.LIGHTBLUE_700,
                  MaterialColors.LIGHTBLUE_800,
                  MaterialColors.LIGHTBLUE_900,
                  MaterialColors.LIGHTBLUE_A200,
                  MaterialColors.LIGHTBLUE_A400,
                  MaterialColors.LIGHTBLUE_A700,
                  MaterialColors.CYAN_400,
                  MaterialColors.CYAN_500,
                  MaterialColors.CYAN_600,
                  MaterialColors.CYAN_700,
                  MaterialColors.CYAN_800,
                  MaterialColors.CYAN_900,
                  MaterialColors.CYAN_A200,
                  MaterialColors.CYAN_A400,
                  MaterialColors.CYAN_A700,
                  MaterialColors.TEAL_400,
                  MaterialColors.TEAL_500,
                  MaterialColors.TEAL_600,
                  MaterialColors.TEAL_700,
                  MaterialColors.TEAL_800,
                  MaterialColors.TEAL_900,
                  MaterialColors.TEAL_A200,
                  MaterialColors.TEAL_A400,
                  MaterialColors.TEAL_A700,
                  MaterialColors.GREEN_400,
                  MaterialColors.GREEN_500,
                  MaterialColors.GREEN_600,
                  MaterialColors.GREEN_700,
                  MaterialColors.GREEN_800,
                  MaterialColors.GREEN_900,
                  MaterialColors.GREEN_A200,
                  MaterialColors.GREEN_A400,
                  MaterialColors.GREEN_A700,
                  MaterialColors.LIGHTGREEN_400,
                  MaterialColors.LIGHTGREEN_500,
                  MaterialColors.LIGHTGREEN_600,
                  MaterialColors.LIGHTGREEN_700,
                  MaterialColors.LIGHTGREEN_800,
                  MaterialColors.LIGHTGREEN_900,
                  MaterialColors.LIGHTGREEN_A200,
                  MaterialColors.LIGHTGREEN_A400,
                  MaterialColors.lightgreen_A700,
                  MaterialColors.LIME_400,
                  MaterialColors.LIME_500,
                  MaterialColors.LIME_600,
                  MaterialColors.LIME_700,
                  MaterialColors.LIME_800,
                  MaterialColors.LIME_900,
                  MaterialColors.LIME_A200,
                  MaterialColors.LIME_A400,
                  MaterialColors.LIME_A700,
                  MaterialColors.YELLOW_400,
                  MaterialColors.YELLOW_500,
                  MaterialColors.YELLOW_600,
                  MaterialColors.YELLOW_700,
                  MaterialColors.YELLOW_800,
                  MaterialColors.YELLOW_900,
                  MaterialColors.YELLOW_A200,
                  MaterialColors.YELLOW_A400,
                  MaterialColors.YELLOW_A700,
                  MaterialColors.AMBER_400,
                  MaterialColors.AMBER_500,
                  MaterialColors.AMBER_600,
                  MaterialColors.AMBER_700,
                  MaterialColors.AMBER_800,
                  MaterialColors.AMBER_900,
                  MaterialColors.AMBER_A200,
                  MaterialColors.AMBER_A400,
                  MaterialColors.AMBER_A700,
                  MaterialColors.ORANGE_400,
                  MaterialColors.ORANGE_500,
                  MaterialColors.ORANGE_600,
                  MaterialColors.ORANGE_700,
                  MaterialColors.ORANGE_800,
                  MaterialColors.ORANGE_900,
                  MaterialColors.ORANGE_A200,
                  MaterialColors.ORANGE_A400,
                  MaterialColors.ORANGE_A700,
                  MaterialColors.DEEPORANGE_400,
                  MaterialColors.DEEPORANGE_500,
                  MaterialColors.DEEPORANGE_600,
                  MaterialColors.DEEPORANGE_700,
                  MaterialColors.DEEPORANGE_800,
                  MaterialColors.DEEPORANGE_900,
                  MaterialColors.DEEPORANGE_A200,
                  MaterialColors.DEEPORANGE_A400,
                  MaterialColors.DEEPORANGE_A700,
                  MaterialColors.BROWN_400,
                  MaterialColors.BROWN_500,
                  MaterialColors.BROWN_600,
                  MaterialColors.BROWN_700,
                  MaterialColors.BROWN_800,
                  MaterialColors.BROWN_900,
                  MaterialColors.GREY_400,
                  MaterialColors.GREY_500,
                  MaterialColors.GREY_600,
                  MaterialColors.GREY_700,
                  MaterialColors.GREY_800,
                  MaterialColors.GREY_900,
                  MaterialColors.BLUEGREY_400,
                  MaterialColors.BLUEGREY_500,
                  MaterialColors.BLUEGREY_600,
                  MaterialColors.BLUEGREY_700,
                  MaterialColors.BLUEGREY_800,
                  MaterialColors.BLUEGREY_900
               )
            )
        }

        private fun create(colorList: List<Int>): ColorGenerator {
            return ColorGenerator(colorList)
        }
    }
}